### ISSUE TITLE
`AttributeError: 'Namespace' object has no attribute 'func'`

### ISSUE THREAD

**Issue by jhotta** [DataDog/datadogpy#85]
Environment
- python 3.4.3
- w/ pyenv

case without option:
/Users/papago% dog timeboard

```
Traceback (most recent call last):
  File "/Users/papago/.pyenv/versions/3.4.3/bin/dog", line 9, in <module>
    load_entry_point('datadog==0.9.0', 'console_scripts', 'dog')()
  File "/Users/papago/.pyenv/versions/3.4.3/lib/python3.4/site-packages/datadog/dogshell/__init__.py", line 74, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

case with -h option:
/Users/papago% dog timeboard -h

```
usage: dog timeboard [-h] [--string_ids]
                     {post,update,show,show_all,pull,pull_all,push,new_file,web_view,delete}
                     ...

optional arguments:
  -h, --help            show this help message and exit
  --string_ids          Represent timeboard IDs as strings instead of ints in
                        JSON

Verbs:
  {post,update,show,show_all,pull,pull_all,push,new_file,web_view,delete}
    post                Create timeboards
    update              Update existing timeboards
    show                Show a timeboard definition
    show_all            Show a list of all timeboards
    pull                Pull a timeboard on the server into a local file
    pull_all            Pull all timeboards into files in a directory
    push                Push updates to timeboards from local files to the
                        server
    new_file            Create a new timeboard and put its contents in a file
    web_view            View the timeboard in a web browser
    delete              Delete timeboards
/Users/papago% 
```

**Comment by yannmh** [comment]
Thanks for reporting @jhotta.

We'll work on a fix for the upcoming 0.11.0 release.
