### ISSUE TITLE
Positional argument names of DogStatsd.event, ThreadStats.event differ in 0.43.0

### ISSUE THREAD

**Issue by aaronlutz** [DataDog/datadogpy#707]
**Describe the bug**

* In [0.42.0](https://github.com/DataDog/datadogpy/tree/v0.42.0) [`datadog.ThreadStats.event()`](https://github.com/DataDog/datadogpy/blob/v0.42.0/datadog/threadstats/base.py#L177) and [`datadog.DogStatsd.event()`](https://github.com/DataDog/datadogpy/blob/v0.42.0/datadog/dogstatsd/base.py#L695) had **identical positional and keyword arguments**. 
* In [0.43.0](https://github.com/DataDog/datadogpy/tree/v0.43.0):
  * [`datadog.ThreadStats.event()`](https://github.com/DataDog/datadogpy/blob/v0.43.0/datadog/threadstats/base.py#L177) has the same positional and keyword arguments as it did in [0.24.0](https://github.com/DataDog/datadogpy/blob/v0.42.0/datadog/threadstats/base.py#L177)
  * [`datadog.DogStatsd.event()`](https://github.com/DataDog/datadogpy/blob/v0.43.0/datadog/dogstatsd/base.py#L853) **had it's second positional argument renamed from `text` to `message`**
  * Now `datadog.DogStatsd.event()` and `datadog.ThreadStats.event()` arguments are  not fully interchangeable

**To Reproduce**

```bash
$ pip install --upgrade datadog==0.42.0
$ touch alerting.py
```

In `alerting.py`
```python
import os
import datadog

datadog.initialize(
    api_key=os.environ.get('DATADOG_API_KEY'),
    app_key=os.environ.get('DATADOG_APP_KEY'),
)

if os.environ.get('DATADOG_USE_DOGSTATSD'):
    datadog = datadog.DogStatsd()
else:
    datadog = datadog.ThreadStats()
    datadog.start()
```
```
$ DATADOG_API_KEY=foo DATADOG_APP_KEY=bar python
>>> import alerting
>>> alerting.datadog.event(
...    title='EventTitle',
...    text= 'EventBody',
...    alert_type='info',
... )
```
```
$ DATADOG_API_KEY=foo DATADOG_APP_KEY=bar DATADOG_USE_DOGSTATSD=true python
>>> import alerting
>>> alerting.datadog.event(
...    title='EventTitle',
...    text= 'EventBody',
...    alert_type='info',
... )
```
```bash
$ pip install --upgrade datadog==0.43.0
```
```
$ DATADOG_API_KEY=foo DATADOG_APP_KEY=bar python
>>> import alerting
>>> alerting.datadog.event(
...    title='EventTitle',
...    text= 'EventBody',
...    alert_type='info',
... )
```
```
$ DATADOG_API_KEY=foo DATADOG_APP_KEY=bar DATADOG_USE_DOGSTATSD=true python
>>> import alerting
>>> alerting.datadog.event(
...    title='EventTitle',
...    text= 'EventBody',
...    alert_type='info',
... )
TypeError: event() got an unexpected keyword argument 'text'
```

**Expected behavior**

Given the same `*args` and `**kwargs`, `datadog.DogStatsd.event()` and `datadog.ThreadStats.event()` should be interchangeable.

**Environment and Versions (please complete the following information):**

* our `requirements.txt` had `datadog>=0.32.0`
* we have a library which was using `0.42.0` and has an `alerting` module similar to the example above
  * we use `datadog.DogStatsd` in gitlab-ci and in our docker-images running in Airflow
  * we use `datadog.ThreadStats` locally
* in our project which manages our ETLs we had `datadog>=0.32.0`, when `0.43.0` became available it was used in a build today, and started causing failures because the positional and keyword arguments of the two `.event` methods were no longer interchangeable.
* we were able to solve the issue by locking onto version `0.42.0`

**Comment by aaronlutz** [comment]
I don't have sufficient repository permissions to apply the [`backward-incompatible` label](https://github.com/DataDog/datadogpy/blob/2d413f8d6c6000d919900590d0f38dd226940440/CONTRIBUTING.md#:~:text=backward%2Dincompatible) or [`resource/dogstatsd` label](https://github.com/DataDog/datadogpy/blob/2d413f8d6c6000d919900590d0f38dd226940440/CONTRIBUTING.md#:~:text=issue%20or%20changes.-,resource/dogstatsd,-Issues%20and%20Pull).

**Comment by Jltp1972** [comment]
Ran into this today when we updated from 0.42.0 to 0.43.0. Changing the `text` param to `message` solved it, but this seems like kind of a silly backwards-incompatible change.

Our basic usage:

```
import os

from datadog.dogstatsd.base import DogStatsd

statsd = DogStatsd(
    host=os.getenv('DATADOG_HOST', ''),
    namespace='sample-service',
    constant_tags=[
        'application:sample-service',
        'environment:{}'.format(os.getenv('ENVIRONMENT', ''))
    ],
)

def process() -> None:
    statsd.event(title='Sample service process', text='started')
```

**Comment by sgnn7** [comment]
Hey @aaronlutz / @Jltp1972,
Apologies for the delay on answering this. The reason for the change was that it did not align to [service_check](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L926) variable naming so `text` was changed to `message` and it was not flagged as `backwards-incompatible` because it is/was a positional argument. Given your feedback about your use cases via named arguments for positional args, the second assumption did not seem to hold fully for all users so this will be something that we'll be more careful in `statsd` package going forward. With that said and the length of time the release has been out, the impact seems relatively low to the users other than ensuring that ThreadStats API matches in the future so I will see about opening a PR for that for the next release.

**Comment by sgnn7** [comment]
@aaronlutz / @Jltp1972 Consistency fix is merged so I expect 0.43.1+ to have it. In the meantime, you should be able to remove the explicit names on the `title` and `text`/`message` positional parameters for interchangeability between the two packages.
